Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Information

Jwt:
  RefreshTokenExpirationTimeMinutes: 2000
  TokenExpirationTimeMinutes: 15

Swagger:
  Title: "Identity API"

Email:
  From: "Eshop"
  Host: "smtp.gmail.com"
  Port: 587
  Username: "akber.sharifov2004@gmail.com"
  Password: "ueey qfia bnyx atce"

AllowedHosts: "*"
