Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Information

Serilog:
    Using: [Serilog.Sinks.Console, Serilog.Sinks.Seq]
    MinimumLevel: 
      Default: Debug
      Override:
        Microsoft: Information
    WriteTo:
    - Name: Console
    - Name: Seq
      Args: 
        serverUrl: http://seq:5341
    Enrich: [FromLogContext, WithMachineName, WithProcessId]



Jwt:
  RefreshTokenExpirationTimeMinutes: 2000
  TokenExpirationTimeMinutes: 15

Swagger:
  Title: "Book api"

Email:
  From: "Eshop"
  Host: "smtp.gmail.com"
  Port: 587
  Username: "akber.sharifov2004@gmail.com"
  Password: "ueey qfia bnyx atce"

AllowedHosts: "*"
