Logging:
  LogLevel:
    Default: Information
    Microsoft.AspNetCore: Information

Serilog:
    Using: [Serilog.Sinks.Console, Serilog.Sinks.Seq]
    MinimumLevel: 
      Default: Debug
      Override:
        Microsoft: Information
    WriteTo:
    - Name: Console
    - Name: Seq
      Args: 
        serverUrl: http://seq:5341
    Enrich: [FromLogContext, WithMachineName, WithProcessId]

Jwt:
  RefreshTokenExpirationTimeMinutes: 2000
  TokenExpirationTimeMinutes: 40

Swagger:
  Title: "Book api"

AllowedHosts: "*"
