global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'book_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['book.api:80']

  - job_name: 'order_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['order.api:80']

  - job_name: 'email_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['email.api:80']

  - job_name: 'monitoring_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['monitoring.api:80']
