global:
  scrape_interval: 10s

scrape_configs:
- job_name: "email-api"
  static_configs:
  - targets: ["email.api"]
- job_name: "email-app"
  static_configs:
  - targets: ["book.api"]
- job_name: "rabbitmq"
  static_configs:
  - targets: ["rabbitmq:15692"]
  
remote_write:
- url: http://grafana:3000
  basic_auth:
    username: admin
    password: admin