version: '3.4'

services:
  book.api:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=6060
    - ASPNETCORE_HTTPS_PORTS=6061
    # custom environment variables
    - POSTGRE_CONNECTION_STRING=Server=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};TimeZone=UTC;
    - REDIS_CONNECTION_STRING=redis:6379,password=${REDIS_PASSWORD}
    - AUTH_ISSUER=${AUTH_ISSUER}
    - WEB_AUDIENCE=${WEB_AUDIENCE}
    - JWT_SECURITY_KEY=${JWT_SECURITY_KEY}
    - IDENTITY_ENDPOINT=${IDENTITY_ENDPOINT}
    - SERVER_ACCESS_KEY=minio-access-key
    - SERVER_SECRET_KEY=minio-secret-key
    ports:
    - 6060:6060
    - 6061:6061
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  monitoring.api:
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_HTTP_PORTS=8080
    - ASPNETCORE_HTTPS_PORTS=8081
    # custom environment variables
    - HealthChecksUI__HealthChecks__0__Name=Book api
    - HealthChecksUI__HealthChecks__0__Uri=http://book.api/health
    ports:
    - 8080:8080
    - 8081:8081
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  postgres:
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432

  pgadmin:  
    ports:
      - "8087:80"
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
    - pgadmin:/var/lib/pgadmin

  redis:
    environment:
    - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
    - redis:/data
    ports:
    - 6379:6379
  
  seq:
    environment:
    - ACCEPT_EULA=Y
    ports:
    - 5341:5341
    - 7070:80
    volumes:
    - seq:/data
  
  minio:
  #   networks:
  #   - app-tier
    ports:
    - 9000:9000
    - 9001:9001
    environment:
    - MINIO_ROOT_USER=${MINIO_ROOT_USER}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
    - minio:/data
   

volumes:
  minio:
  pgadmin:
  postgres:
  redis:  
  seq:

networks:
  app_tier:
    driver: bridge

