version: '3.4'

services:
  book.api:
    container_name: book.api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: . 
      dockerfile: ../Services/Book/Api/Dockerfile
    depends_on:
    - postgres
    - redis
    
  monitoring.api:
    container_name: monitoring.api
    image: ${DOCKER_REGISTRY-}monitoringapi
    build:
      context: .
      dockerfile: ../Services/Monitoring/Monitoring.Api/Dockerfile

  postgres:
    container_name: postgres
    image: postgres:latest
  
  redis:
    container_name: redis
    image: redis:latest

