version: '3.4'

services:
  book.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  postgres:
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
    volumes:
    - postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432

  redis:
    environment:
    - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
    - redis:/data
    ports:
    - 6379:6379

volumes:
  postgres:
  redis:  
