version: '3.4'

services:
  book.api:
    container_name: book.api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: . 
      dockerfile: ../Services/Book/Api/Dockerfile
    depends_on:
    - postgres
    - redis
    
  monitoring.api:
    container_name: monitoring.api
    image: ${DOCKER_REGISTRY-}monitoringapi
    build:
      context: .
      dockerfile: ../Services/Monitoring/Monitoring.Api/Dockerfile
    depends_on:
    - book.api

  postgres:
    container_name: postgres
    image: postgres:latest

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
  
  redis:
    container_name: redis
    image: redis:latest

  seq:
    container_name: seq
    image: datalust/seq:latest

  minio:
    container_name: minio
    image: quay.io/minio/minio

