version: '3.4'

services:
  postgres:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8087:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: always

  redis:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always

  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "7076:80"
    volumes:
      - seq:/data
    restart: always

  minio:
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    restart: always

  rabbitmq:
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER} 
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_CONFIG_FILE=./configs/rabbitmq.conf
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  prometheus:
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    ports:
      - 3003:3000
    volumes:
      - grafana:/etc/grafana/provisioning
    restart: always

  nginx:
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: always

  book.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRE_CONNECTION_STRING=Server=postgres;Port=5432;Include Error Detail=True;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};TimeZone=UTC;
      - REDIS_CONNECTION_STRING=redis:6379,password=${REDIS_PASSWORD}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - WEB_AUDIENCE=${WEB_AUDIENCE}
      - JWT_SECURITY_KEY=${JWT_SECURITY_KEY}
      - IDENTITY_ENDPOINT=${IDENTITY_ENDPOINT}
      - SERVER_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - SERVER_SECRET_KEY=${MINIO_SECRET_KEY}
      - GOOGLE_ID=${GOOGLE_ID}
      - GRPC_PORT=${GRPC_PORT}
      - HTTP_PORT=${HTTP_PORT}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS} 
      - SERVER_ENDPOINT=minio
    ports:
    - 8939:80 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always

  order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - POSTGRE_CONNECTION_STRING=Server=postgres;Port=5432;Include Error Detail=True;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};TimeZone=UTC;
      - REDIS_CONNECTION_STRING=redis:6379,password=${REDIS_PASSWORD}
      - AUTH_ISSUER=${AUTH_ISSUER}
      - WEB_AUDIENCE=${WEB_AUDIENCE}
      - JWT_SECURITY_KEY=${JWT_SECURITY_KEY}
      - IDENTITY_ENDPOINT=${IDENTITY_ENDPOINT}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
    - 6077:80 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always

  email.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS} 
      - USER_GRPC_URL=${USER_GRPC_URL}
      - IdentityEndpoint__BaseUrl=${IdentityEndpoint__BaseUrl} 
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always
   
  monitoring.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - Email__From=${EMAIL_FROM} 
      - Email__Host=${EMAIL_HOST}
      - Email__Port=${EMAIL_PORT}
      - Email__Username=${EMAIL_USERNAME}
      - Email__Password=${EMAIL_PASSWORD}
      - HealthChecksUI__HealthChecks__0__Name=Book API
      - HealthChecksUI__HealthChecks__0__Uri=http://book.api:80/health
      - HealthChecksUI__HealthChecks__1__Name=Order API
      - HealthChecksUI__HealthChecks__1__Uri=http://email.api:80/health
      - HealthChecksUI__HealthChecks__2__Name=Email API
      - HealthChecksUI__HealthChecks__2__Uri=http://email.api:80/health
      - HealthChecksUI__Webhooks__0__Name=Telegram
      - HealthChecksUI__Webhooks__0__Uri=https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}
      - HealthChecksUI__Webhooks__0__Payload=${TELEGRAM_PAYLOAD}
      - HealthChecksUI__Webhooks__0__RestoredPayload=${TELEGRAM_RESTORED_PAYLOAD}
      - HealthChecksUI__EvaluationTimeInSeconds=10
    ports:
    - 6060:80  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    restart: always

volumes:
  rabbitmq:
  grafana:
  minio:
  pgadmin:
  postgres:
  redis:
  seq:
  nginx:
