version: '3.4'

services:
  book.api:
    container_name: book.api
    image: ${DOCKER_REGISTRY-}api
    build:
      context: . 
      dockerfile: ../Services/Book/Api/Dockerfile
    depends_on:
    - book.api.database
    - book.api.cache

  postgres:
    container_name: postgres
    image: postgres:latest
  
  redis:
    container_name: redis
    image: redis:latest
    